Repository PythonistaGuild/TwitchIO, pull requests merged in 2024-06, with the labels that each got.

#451 Fix fetch_markers passing list instead of dict
  docs/changelog.rst
  twitchio/user.py
Labels: bug, HTTP, 2.0

#455 Update master with V2.10.0
  docs/changelog.rst
  docs/exts/eventsub.rst
  docs/requirements.txt
  setup.py
  twitchio/__init__.py
  twitchio/errors.py
  twitchio/ext/commands/bot.py
  twitchio/ext/commands/errors.py
  twitchio/ext/commands/stringparser.py
  twitchio/ext/eventsub/models.py
  twitchio/ext/eventsub/server.py
  twitchio/ext/eventsub/websocket.py
  twitchio/ext/pubsub/models.py
  twitchio/ext/pubsub/pool.py
  twitchio/ext/pubsub/topics.py
  twitchio/ext/pubsub/websocket.py
  twitchio/ext/sounds/__init__.py
  twitchio/models.py
  twitchio/user.py
Labels: 2.0

#456 Rework GitHub Actions to correctly and sanely push to PyPi in a controlled manner
  .github/dependabot.yaml
  .github/workflows/build.yml
  .github/workflows/edit_version.py
  .github/workflows/get_revision.py
  .github/workflows/publish.yml
Labels: new feature
